# Comment that will be sent if an issue is judged to be closed.
comment: "This issue is closed because it does not meet our issue template. Please read it."
issueConfigs:
# There can be several configs for different kind of issues.
- content:
# Example 1: bug report
  - "Describe the bug"
  - "To Reproduce"
  - "Expected behavior"
  - "Current Behavior"
  - "Screenshots"
  - "Desktop (please complete the following information):"
  - "Smartphone (please complete the following information):"
  - "Additional context"
- content:
# Example 2: feature request
  - "Is your feature request related to a problem? Please describe."
  - "Describe the solution you'd like"
  - "Describe alternatives you've considered"
  - "Additional context"
- content:
# Example 3: need helps with the plugin
  - "What you try to do"
  - "What is the problem"
  - "What kind of things have you already treated"
  - "Steps to reproduce"
  - "Os"
  - "Mobile"
  - "Versions"
  - "Package manager"
  - "Plugin version"
- content:
# Example 4: vulnerability
  - "Vulnerability type"
  - "Vulnerability place"
  - "How do you found it?"
  - "How do you think that it can be fixed? (optional)"
  - "Os"
  - "Mobile"
  - "Versions"
  - "Package manager"
  - "Plugin version"
# Optional configuration:
#
# whether the keywords are case-insensitive
# default value is false, which means keywords are case-sensitive
caseInsensitive: false
# the label that will be added when the bot close an issue
# The bot will only add a label if this property is set.
label: "closed by bot"
# The bot will ignore any issues that are opened or reopened by the user names in exception
exception:
  - "diegoazh"
  - "dgaletto"
# The issue is judged to be legal if it includes all keywords from any of these two configs.
# Or it will be closed by the app.
